// GENERATED by scripts/compile-home-shaders.mjs. Edit the recipe, not this file.
// FlowingGradient + Aurora + FilmGrain + DotGrid, shaders@4.0.4.
/*
MIT License

Copyright (c) 2026 Shader Effects Inc.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
struct item_1 {
  time: f32,
  deltaTime: f32,
  frame: f32,
  viewportSize: vec2f,
  logicalViewportSize: vec2f,
  aspect: f32,
  pointer: vec2f,
  pointerActive: f32,
}

struct item {
  _sys: item_1,
}

@group(0) @binding(0) var<uniform> uniforms: item;

fn mxFade(t: f32) -> f32 {
  return (((t * t) * t) * ((t * ((t * 6f) - 15f)) + 10f));
}

fn mxRotl32(x: u32, k: i32) -> u32 {
  return ((x << u32(k)) | (x >> u32((32i - k))));
}

fn mxBjfinal(a0: u32, b0: u32, c0: u32) -> u32 {
  var a = a0;
  var b = b0;
  var c = c0;
  c = (c ^ b);
  c = (c - mxRotl32(b, 14i));
  a = (a ^ c);
  a = (a - mxRotl32(c, 11i));
  b = (b ^ a);
  b = (b - mxRotl32(a, 25i));
  c = (c ^ b);
  c = (c - mxRotl32(b, 16i));
  a = (a ^ c);
  a = (a - mxRotl32(c, 4i));
  b = (b ^ a);
  b = (b - mxRotl32(a, 14i));
  c = (c ^ b);
  c = (c - mxRotl32(b, 24i));
  return c;
}

fn mxHashInt2(x: i32, y: i32, z: i32) -> u32 {
  const len = 3u;
  let seed = ((3735928559u + (len << 2u)) + 13u);
  let a = (seed + u32(x));
  let b = (seed + u32(y));
  let c = (seed + u32(z));
  return mxBjfinal(a, b, c);
}

fn mxGradientFloat3(hash: u32, x: f32, y: f32, z: f32) -> f32 {
  let h = (hash & 15u);
  let u = select(y, x, (h < 8u));
  let inner = select(z, x, ((h == 12u) || (h == 14u)));
  let v = select(inner, y, (h < 4u));
  let uu = select(u, -(u), ((h & 1u) != 0u));
  let vv = select(v, -(v), ((h & 2u) != 0u));
  return (uu + vv);
}

fn mxTrilerp(v0: f32, v1: f32, v2: f32, v3: f32, v4: f32, v5: f32, v6: f32, v7: f32, s: f32, t: f32, r: f32) -> f32 {
  let s1 = (1f - s);
  let t1 = (1f - t);
  let r1 = (1f - r);
  return ((r1 * ((t1 * ((v0 * s1) + (v1 * s))) + (t * ((v2 * s1) + (v3 * s))))) + (r * ((t1 * ((v4 * s1) + (v5 * s))) + (t * ((v6 * s1) + (v7 * s))))));
}

fn mxGradientScale3d(v: f32) -> f32 {
  return (0.982f * v);
}

fn mxPerlinNoiseFloat3(p: vec3f) -> f32 {
  let X = i32(floor(p.x));
  let Y = i32(floor(p.y));
  let Z = i32(floor(p.z));
  let fx = (p.x - f32(X));
  let fy = (p.y - f32(Y));
  let fz = (p.z - f32(Z));
  let u = mxFade(fx);
  let v = mxFade(fy);
  let w = mxFade(fz);
  let result = mxTrilerp(mxGradientFloat3(mxHashInt2(X, Y, Z), fx, fy, fz), mxGradientFloat3(mxHashInt2((X + 1i), Y, Z), (fx - 1f), fy, fz), mxGradientFloat3(mxHashInt2(X, (Y + 1i), Z), fx, (fy - 1f), fz), mxGradientFloat3(mxHashInt2((X + 1i), (Y + 1i), Z), (fx - 1f), (fy - 1f), fz), mxGradientFloat3(mxHashInt2(X, Y, (Z + 1i)), fx, fy, (fz - 1f)), mxGradientFloat3(mxHashInt2((X + 1i), Y, (Z + 1i)), (fx - 1f), fy, (fz - 1f)), mxGradientFloat3(mxHashInt2(X, (Y + 1i), (Z + 1i)), fx, (fy - 1f), (fz - 1f)), mxGradientFloat3(mxHashInt2((X + 1i), (Y + 1i), (Z + 1i)), (fx - 1f), (fy - 1f), (fz - 1f)), u, v, w);
  return mxGradientScale3d(result);
}

fn mxNoiseFloat3(p: vec3f) -> f32 {
  return mxPerlinNoiseFloat3(p);
}

fn chainedWarpStep(pos: vec2f, scale: f32, z: f32, offA: vec2f, offB: vec2f, k: f32, strength: f32) -> vec4f {
  let wp = vec3f((pos.x * scale), (pos.y * scale), z);
  let nx = mxNoiseFloat3((wp + vec3f(offA.x, offA.y, 0f)));
  let ny = mxNoiseFloat3((wp + vec3f(offB.x, offB.y, 0f)));
  return vec4f((pos.x + ((nx * k) * strength)), (pos.y + ((ny * k) * strength)), nx, ny);
}

fn awMix(a: vec3f, b: vec3f, wA: f32, wB: f32, sw: f32) -> vec3f {
  return (((a * wA) + (b * wB)) / sw);
}

fn mixColors(colorA: vec4f, colorB: vec4f, t: f32) -> vec4f {
  let weightA = (colorA.w * (1f - t));
  let weightB = (colorB.w * t);
  let totalWeight = (weightA + weightB);
  let safeWeight = max(totalWeight, 1e-3f);
  let rgb = awMix(colorA.xyz, colorB.xyz, weightA, weightB, safeWeight);
  return vec4f(rgb, totalWeight);
}

fn floatBitsToUint2(v: vec2f) -> vec2u { return bitcast<vec2u>(v); }

fn hash12(p: vec2f) -> f32 {
  let u = floatBitsToUint2((p * vec2f(141421360, 2718281728)));
  return (f32(((u.x ^ u.y) * 3141592653u)) / 4294967296f);
}

fn filmGrain(color: vec4f, uv: vec2f, viewport: vec2f, strength: f32, bias: f32, animTime: f32) -> vec4f {
  let pixelCoord = (uv * viewport);
  let noiseVal = hash12((pixelCoord + vec2f(animTime, (animTime * 1.6180339f))));
  let grain = ((noiseVal * 2f) - 1f);
  let brightness = clamp(dot(color.xyz, vec3f(0.2125999927520752, 0.7152000069618225, 0.0722000002861023)), 0f, 1f);
  let darkness = (1f - brightness);
  let darkFactor = pow((darkness + 1e-6f), bias);
  let grainIntensity = ((grain * darkFactor) * (strength * 0.1f));
  let grainedColor = (color.xyz + grainIntensity);
  return vec4f(grainedColor, color.w);
}

fn overComposite(base: vec4f, blended: vec3f, overlayAlpha: f32) -> vec4f {
  let baseWeight = (base.w * (1f - overlayAlpha));
  let finalAlpha = (overlayAlpha + baseWeight);
  let rgb = ((blended * overlayAlpha) + (base.xyz * baseWeight));
  return vec4f(rgb, finalAlpha);
}

fn blend_normal(base: vec4f, overlay: vec4f, opacity: f32) -> vec4f {
  let overlayAlpha = (overlay.w * opacity);
  return overComposite(base, overlay.xyz, overlayAlpha);
}

fn blend_screen(base: vec4f, overlay: vec4f, opacity: f32) -> vec4f {
  let overlayAlpha = (overlay.w * opacity);
  let blended = (1f - ((1f - base.xyz) * (1f - overlay.xyz)));
  return overComposite(base, blended, overlayAlpha);
}

fn aspectCorrectedUVFlipY(uv: vec2f, viewport: vec2f) -> vec2f {
  let aspect = (viewport.x / max(viewport.y, 1e-6f));
  return vec2f((uv.x * aspect), (1f - uv.y));
}

fn rowSpeedHash(row: f32) -> f32 {
  return fract((sin((row * 127.1f)) * 43758.5453f));
}

fn rowSpeedMultiplier(rowHash: f32, variance: f32) -> f32 {
  return (1f + (((rowHash - 0.5f) * 4f) * variance));
}

fn flooredMod1(x: f32, m: f32) -> f32 {
  return (x - (m * floor((x / m))));
}

struct CellTile {
  cell: vec2f,
  local: vec2f,
}

fn squareTiling(p: vec2f) -> CellTile {
  return CellTile(floor(p), fract(p));
}

fn discCoverage(dist: f32, radius: f32, footprint: f32) -> f32 {
  return (1f - smoothstep((radius - (footprint * 0.5f)), radius, dist));
}

fn dotGridAlpha(uv: vec2f, viewport: vec2f, density: f32, dotSize: f32, offset: f32, speedVariance: f32, twinkle: f32, animTime: f32, time: f32) -> f32 {
  let correctedUV = aspectCorrectedUVFlipY(uv, viewport);
  let gridUV = (correctedUV * density);
  let rowIndex = floor(gridUV.y);
  let speedMod = rowSpeedMultiplier(rowSpeedHash(rowIndex), speedVariance);
  let drift = (animTime * speedMod);
  let staticStagger = (offset * flooredMod1(rowIndex, 2f));
  let shiftedGrid = vec2f(((gridUV.x - staticStagger) - drift), gridUV.y);
  let tile = squareTiling(shiftedGrid);
  let centerDistance = length((tile.local - 0.5f));
  let pixelSize = length(fwidth((correctedUV * density)));
  let coverage = discCoverage(centerDistance, (dotSize * 0.5f), pixelSize);
  let dotPhase = fract((sin(((tile.cell.x * 12.9898f) + (tile.cell.y * 78.233f))) * 43758.5453f));
  let twinkleTime = ((time * 2f) + (dotPhase * 6.283185307179586f));
  let twinkleValue = ((sin(twinkleTime) * 0.5f) + 0.5f);
  let twinkleModifier = mix(1f, twinkleValue, twinkle);
  return (coverage * twinkleModifier);
}

fn linearToSrgb(color: vec3f) -> vec3f {
  let a = ((pow(color, vec3f(0.41666001081466675)) * 1.055f) - 0.055f);
  let b = (color * 12.92f);
  let factor = (color <= vec3f(0.0031308000907301903));
  return select(a, b, factor);
}

fn tone_linear(color: vec3f) -> vec3f {
  return vec3f(color.x, color.y, color.z);
}

struct final_Input {
  @location(0) uv: vec2f,
}

@fragment fn fragment(in: final_Input) -> @location(0)  vec4f {
  var uv = vec2f(in.uv.x, 1.0 - in.uv.y);
  let flowCentred_9 = (uv - 0.5);
  let aspect_10 = (uniforms._sys.viewportSize.x / max(uniforms._sys.viewportSize.y, 0.000001));
  let flowTime_12 = ((uniforms._sys.time * 2.4) * 0.075);
  let flowSeed_13 = (4.0 * 0.17);
  let flowStrength_14 = 0.7;
  let flowAngle_11 = ((mxNoiseFloat3(vec3f(((flowCentred_9.x * 0.8) + (flowTime_12 * 0.4)), ((flowCentred_9.y * 0.8) - (flowTime_12 * 0.25)), flowSeed_13)) * 12.566370614359172) * flowStrength_14);
  let flowSpun_8 = vec2f((((vec2f(flowCentred_9.x, (flowCentred_9.y / aspect_10))).x * cos(flowAngle_11)) - ((vec2f(flowCentred_9.x, (flowCentred_9.y / aspect_10))).y * sin(flowAngle_11))), (((vec2f(flowCentred_9.x, (flowCentred_9.y / aspect_10))).x * sin(flowAngle_11)) + ((vec2f(flowCentred_9.x, (flowCentred_9.y / aspect_10))).y * cos(flowAngle_11))));
  let flowRot_7 = vec2f(flowSpun_8.x, (flowSpun_8.y * aspect_10));
  let flowShearX_6 = (flowRot_7.x + ((sin(((flowRot_7.y * 5.0) + (flowTime_12 * 2.0))) / 50.0) * flowStrength_14));
  let flowWarp1_5 = chainedWarpStep(vec2f(flowShearX_6, (flowRot_7.y + ((sin(((flowShearX_6 * 7.5) + (flowTime_12 * 2.0))) / 25.0) * flowStrength_14))), 2.0, ((flowTime_12 * 0.5) + flowSeed_13), vec2f(5.2, 1.3), vec2f(1.7, 9.2), 0.25, flowStrength_14);
  let flowHardness_4 = pow(((flowWarp1_5.z * 0.5) + 0.5), 1.5);
  let flowEdge_3 = mix(0.5, 0.008, flowHardness_4);
  let flowTz_16 = ((flowTime_12 * 0.3) + flowSeed_13);
  let flowWarp2_15 = chainedWarpStep(flowWarp1_5.xy, 1.5, flowTz_16, vec2f(8.3, 2.8), vec2f(3.1, 7.4), 0.2, flowStrength_14);
  let flowT1_2 = smoothstep((flowEdge_3 * -1.0), flowEdge_3, mxNoiseFloat3(vec3f((flowWarp2_15.x * 1.8), (flowWarp2_15.y * 1.8), flowTz_16)));
  let flowRow1_1 = mixColors(vec4f(0.003920815891725075, 0.007857622872494007, 0.027544795814230114, 1.0), vec4f(0.04383677947144446, 0.14852335349378037, 0.32709899668855197, 1.0), flowT1_2);
  let flowRow2_17 = mixColors(vec4f(0.16532512460671275, 0.12388175418254778, 0.412142590158982, 1.0), vec4f(0.35338296106579586, 0.5685319299878593, 0.6528737266588001, 1.0), flowT1_2);
  let flowT2_18 = smoothstep((flowEdge_3 * -1.0), flowEdge_3, flowWarp1_5.w);
  let flowBase_0 = mixColors(flowRow1_1, flowRow2_17, flowT2_18);
  let aspect_23 = (uniforms._sys.viewportSize.x / max(uniforms._sys.viewportSize.y, 0.000001));
  let wx_22 = (((uv.x - (vec2f(0.5, 1.0)).x) * aspect_23) * 2.0);
  let auroraTime_25 = (uniforms._sys.time * 0.8);
  let tSlow_24 = ((auroraTime_25 * 0.06) + 0.0);
  let lSeed_26 = (0.0 + 0.0);
  let curtainNoise_27 = mxNoiseFloat3(vec3f((wx_22 * 0.5), (tSlow_24 * 0.25), (lSeed_26 * 0.1)));
  let distFromPath_21 = (uv.y - (((1.0 - (vec2f(0.5, 1.0)).y) + ((((sin((((wx_22 * 0.7) + (tSlow_24 * 0.4)) + (fract((sin((lSeed_26 * 12.9)) * 4758.5)) * 6.283185307179586))) * 0.15) + (sin((((wx_22 * 1.6) + (tSlow_24 * 0.65)) + (fract((sin((lSeed_26 * 78.2)) * 2847.1)) * 6.283185307179586))) * 0.08)) + (sin((((wx_22 * 2.9) + (tSlow_24 * 0.3)) + (fract((sin((lSeed_26 * 41.6)) * 1593.7)) * 6.283185307179586))) * 0.04)) * (50.0 * 0.01))) + ((curtainNoise_27 * 0.14) * (50.0 * 0.01))));
  let curtainRays_29 = pow(((sin(((((wx_22 + (curtainNoise_27 * 2.5)) * (mix(6.0, 20.0, (20.0 * 0.01)) * 0.15)) + (tSlow_24 * 0.1)) + (fract((sin((lSeed_26 * 53.7)) * 3847.2)) * 6.283185307179586))) * 0.5) + 0.5), 1.5);
  let topExtent_28 = (((140.0 * 0.01) * mix(0.4, 1.0, curtainRays_29)) * ((curtainRays_29 * 0.4) + 0.6));
  let colorT_20 = clamp((distFromPath_21 / (topExtent_28 + 0.001)), 0.0, 1.0);
  let curtainAlpha_30 = ((((smoothstep(-0.04, 0.015, distFromPath_21) * (1.0 - smoothstep(0.0, topExtent_28, distFromPath_21))) * curtainRays_29) * mix(0.4, 1.0, ((curtainNoise_27 * 0.5) + 0.5))) * ((exp((((colorT_20 - 0.2) * (colorT_20 - 0.2)) * -6.0)) * 0.3) + 1.0));
  let wx_33 = (((uv.x - (vec2f(0.5, 1.0)).x) * aspect_23) * 2.0);
  let tSlow_34 = ((auroraTime_25 * 0.06) + 3.1);
  let lSeed_35 = (0.0 + 31.700000762939453);
  let curtainNoise_36 = mxNoiseFloat3(vec3f((wx_33 * 0.5), (tSlow_34 * 0.25), (lSeed_35 * 0.1)));
  let distFromPath_32 = (uv.y - (((1.0 - (vec2f(0.5, 1.0)).y) + ((((sin((((wx_33 * 0.7) + (tSlow_34 * 0.4)) + (fract((sin((lSeed_35 * 12.9)) * 4758.5)) * 6.283185307179586))) * 0.15) + (sin((((wx_33 * 1.6) + (tSlow_34 * 0.65)) + (fract((sin((lSeed_35 * 78.2)) * 2847.1)) * 6.283185307179586))) * 0.08)) + (sin((((wx_33 * 2.9) + (tSlow_34 * 0.3)) + (fract((sin((lSeed_35 * 41.6)) * 1593.7)) * 6.283185307179586))) * 0.04)) * (50.0 * 0.01))) + ((curtainNoise_36 * 0.14) * (50.0 * 0.01))));
  let curtainRays_38 = pow(((sin(((((wx_33 + (curtainNoise_36 * 2.5)) * (mix(6.0, 20.0, (20.0 * 0.01)) * 0.15)) + (tSlow_34 * 0.1)) + (fract((sin((lSeed_35 * 53.7)) * 3847.2)) * 6.283185307179586))) * 0.5) + 0.5), 1.5);
  let topExtent_37 = (((140.0 * 0.01) * mix(0.4, 1.0, curtainRays_38)) * ((curtainRays_38 * 0.4) + 0.6));
  let colorT_31 = clamp((distFromPath_32 / (topExtent_37 + 0.001)), 0.0, 1.0);
  let curtainAlpha_39 = ((((smoothstep(-0.04, 0.015, distFromPath_32) * (1.0 - smoothstep(0.0, topExtent_37, distFromPath_32))) * curtainRays_38) * mix(0.4, 1.0, ((curtainNoise_36 * 0.5) + 0.5))) * ((exp((((colorT_31 - 0.2) * (colorT_31 - 0.2)) * -6.0)) * 0.3) + 1.0));
  let auroraAlpha_40 = (curtainAlpha_30 + (curtainAlpha_39 * 0.65));
  let auroraAvgT_19 = pow((((colorT_20 * curtainAlpha_30) + (colorT_31 * (curtainAlpha_39 * 0.65))) / (auroraAlpha_40 + 0.001)), mix(2.5, 0.4, (50.0 * 0.01)));
  let auroraGlow_41 = (auroraAlpha_40 * (55.0 * 0.018));
  var composed_42 = filmGrain(blend_normal(blend_screen(vec4f(clamp((flowBase_0.rgb * (((((flowWarp2_15.z * 0.5) + 0.5) * 0.12) + 0.94) * (1.0 + ((max((1.0 - abs(((flowT1_2 * 2.0) - 1.0))), (1.0 - abs(((flowT2_18 * 2.0) - 1.0)))) * flowHardness_4) * 0.35)))), vec3f(0.0), vec3f(1.0)), flowBase_0.a), vec4f(clamp(((mixColors(mixColors(vec4f(0.13623839555627898, 0.1989200541190927, 0.5664754339375571, 1.0), vec4f(0.42816824664928244, 0.7254093530240687, 0.816027424226805, 1.0), smoothstep(0.0, 0.2, auroraAvgT_19)), vec4f(0.4352400731047213, 0.3411219372263281, 0.6905625881512291, 1.0), smoothstep(0.4, 0.85, auroraAvgT_19))).rgb * auroraGlow_41), vec3f(0.0), vec3f(1.0)), clamp((auroraGlow_41 * 0.5), 0.0, 1.0)), 0.65), vec4f((vec4f(0.6495597345489939, 0.7633648506345654, 0.8976655813087181, 1.0)).rgb, dotGridAlpha(uv, uniforms._sys.viewportSize, 27.0, 0.1, 0.0, 0.3, 0.2, (uniforms._sys.time * 0.03), uniforms._sys.time)), 0.13), uv, uniforms._sys.viewportSize, 0.045, 2.0, 0.0);
  return vec4f(linearToSrgb(tone_linear(composed_42.rgb)) * composed_42.a, composed_42.a);
}

struct HeroVertex { @builtin(position) position: vec4f, @location(0) uv: vec2f }
@vertex fn vertex(@builtin(vertex_index) index: u32) -> HeroVertex {
  let positions = array<vec2f, 3>(vec2f(-1., -1.), vec2f(3., -1.), vec2f(-1., 3.));
  let p = positions[index];
  var out: HeroVertex;
  out.position = vec4f(p, 0., 1.);
  out.uv = vec2f((p.x + 1.) * .5, (1. - p.y) * .5);
  return out;
}
